---
title: "Lab assignment#2 Mixed linear models"
author: "Meier Chen"
date: 'Last edited: `r Sys.Date()`'
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, warning = FALSE, message = FALSE)
```

#### Loading packages	

```{r}
library(tidyverse)  # for dplyr and ggplot
library(psych) # for descriptive analysis
library(lme4) # for lmer	
library(r2glmm) # for r2beta	
library(dominanceanalysis) # for dominanceAnalysis()
library(MuMIn) # for r.squaredGLMM
library(cAIC4)
```

#### Exploring data

```{r}
# loading data
surgeryA_data <- read.csv("https://raw.githubusercontent.com/kekecsz/SIMM61-Course-materials/main/Home_assignment/surgery_data_1.csv")
view(surgeryA_data)
str(surgeryA_data)
surgeryA_data$sex[surgeryA_data$sex == "woman"] <- "female"

surgeryB_data <- read.csv("https://raw.githubusercontent.com/kekecsz/SIMM61-Course-materials/main/Home_assignment/surgery_data_2.csv")
view(surgeryB_data)
str(surgeryB_data)


surgeryA_data <- surgeryA_data %>%
  mutate(hospital = factor(hospital),
         sex = as.factor(sex)) 

surgeryB_data <- surgeryB_data %>%
  mutate(hospital = factor(hospital),
         sex = as.factor(sex))

# descriptive analysis
summary(surgeryA_data)
describe(surgeryA_data)
surgeryA_data %>%
ggplot() + aes(x = pain) + geom_histogram()

summary(surgeryB_data)
describe(surgeryB_data)
```

#### Exploratory analysis

```{r}
# pain : sex
surgeryA_data %>% ggplot(aes(x = sex, fill = pain)) +	geom_bar()

# pain : age
surgeryA_data %>% ggplot() + aes(x = age, y = pain, color = hospital) + geom_point() + stat_smooth(method = lm)

# pain : STAI_trait
surgeryA_data %>% ggplot() + aes(x = STAI_trait, y = pain, color = hospital) + geom_point() + stat_smooth(method = lm)

# pain : pain_cat
surgeryA_data %>% ggplot() + aes(x = pain_cat, y = pain, color = hospital) + geom_point() + stat_smooth(method = lm)

# pain : cortisol_serum
surgeryA_data %>% ggplot() + aes(x = cortisol_serum, y = pain, color = hospital) + geom_point() + stat_smooth(method = lm)

# pain : cortisol_saliva
surgeryA_data %>% ggplot() + aes(x = cortisol_saliva, y = pain, color = hospital) + geom_point() + stat_smooth(method = lm)

# pain : mindfulness
surgeryA_data %>% ggplot() + aes(x = mindfulness, y = pain, color = hospital) + geom_point() + stat_smooth(method = lm)

# pain : weight
surgeryA_data %>% ggplot() + aes(x = weight, y = pain, color = hospital) + geom_point() + stat_smooth(method = lm)

# pain: IQ
surgeryA_data %>% ggplot() + aes(x = IQ, y = pain, color = hospital) + geom_point() + stat_smooth(method = lm)

# pain : household_income
surgeryA_data %>% ggplot() + aes(x = household_income, y = pain, color = hospital) + geom_point() + stat_smooth(method = lm)
```


### Linear mixed model

```{r}
mod_int <- lmer(pain ~ age + sex + STAI_trait + pain_cat + mindfulness +  cortisol_serum + (1 | hospital), data = surgeryA_data)
summary(mod_int)
confint(mod_int)


# marginal R^2 with confidence intervals
r2beta(mod_int, method = "nsj", data = surgeryA_data)  

# marginal and conditional R^2
r.squaredGLMM(mod_int)  
```

### Predict

```{r}
prediction_RSS <- predict(mod_int, newdata = surgeryB_data, re.form = ~0)

RSS <- sum((surgeryB_data$pain - prediction_RSS)^2)

mod_mean <- lm(pain ~ 1, data = surgeryA_data)
prediction_TSS <- predict(mod_mean, surgeryB_data)

TSS <- sum((surgeryB_data$pain - prediction_TSS)^2)

R2 <- 1 - (RSS/TSS)
R2  # 0.3799636

```

### final model

```{r}
# dominance analysis
mod2 <- lm(pain ~ age + sex + STAI_trait + pain_cat + mindfulness +  cortisol_serum, data = surgeryA_data)

dominance_mod2 <- dominanceAnalysis(mod2)

contributionByLevel(dominance_mod2)
plot(dominance_mod2, which.graph ="conditional") + coord_flip()
averageContribution(dominance_mod2)
plot(dominance_mod2, which.graph ="general") + coord_flip()

# fit final model
mod_final <- lmer(pain ~ cortisol_serum + (cortisol_serum | hospital),data = surgeryA_data)
summary(mod_final)

mod_final_control <- lmer(pain ~ cortisol_serum + (cortisol_serum | hospital), control=lmerControl(check.conv.singular = .makeCC(action = "ignore", tol = 1e-4)),data = surgeryA_data)

# visualization
surgeryA_data <- surgeryA_data %>% 
  mutate(pred_slope = predict(mod_final_control))

surgeryA_data %>% 
  ggplot() + aes(y = pain, x = cortisol_serum, group = hospital) +
  geom_point(aes(color = hospital), size = 4) + 
  geom_line(color = "red", aes(y = pred_slope, x = cortisol_serum)) +
  facet_wrap(~hospital, ncol = 5)

# significance and variance explained
r2beta(mod_final_control, method = "nsj", data = surgeryA_data)
r.squaredGLMM(mod_final_control)

 
```

### compare different models

```{r}
mod_compare <- lmer(pain ~ cortisol_serum + (1 | hospital), data = surgeryA_data)
cAIC(mod_compare)$caic  # 664.5371

cAIC(mod_final_control)$caic  # 664.5371

surgeryA_data  = surgeryA_data %>% 
  mutate(pred_int = predict(mod_compare))

surgeryA_data %>% 
  ggplot() + aes(y = pain, x = cortisol_serum, group = hospital) + 
  geom_point(aes(color = hospital), size = 4) + 
  geom_line(color = "red", aes(y = pred_int, x = cortisol_serum)) +
  facet_wrap(~hospital, ncol = 5)
```

