---
title: "Lab assignment#1 Logistic regression"
author: "Meier Chen"
date: 'Last edited: `r Sys.Date()`'
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, warning = FALSE, message = FALSE)
```

#### Loading packages	

```{r}
library(tidyverse)  # for dplyr and ggplot
library(psych) # for descriptive analysis
library(ggpubr) # for ggarrange
library(pscl)  # for pR2
library(dominanceanalysis)  # for dominance analysis
library(lmtest)  # for lrtest
```

#### Loading data

```{r}
titanic_data <- 
  read.csv("https://raw.githubusercontent.com/kekecsz/SIMM61-Course-materials/main/Home_assignment/Titanic%20-%20training%20set.csv", na.strings = c(""))  # load the data and replace all empty values with NA's
view(titanic_data)
```

### Exploring data

```{r}
# Checking data type
str(titanic_data)

# Tidying up the dataset
titanic_data <- titanic_data %>% 
  mutate(Survived = factor((recode(Survived, "0" = "died", "1" = "survived"))),
         Pclass = as_factor(Pclass),
         Sex = as_factor(Sex),
         Pclass3 = recode(Pclass, "1" = "0", "2" = "0", "3" = "1" ),  # "1" = 3rd class ticket, "0" = 1st and 2nd class ticket
         SibSp = as.numeric(SibSp),
         Parch = as.numeric(Parch),
         Embarked = as.factor(Embarked)) %>% 
  mutate(Sex = fct_relevel(Sex, "male")) %>%  # set "male" as reference level
  mutate(Cabin = replace(Cabin, !is.na(Cabin), 1),  # "1" = with cabin(s), "0" = without cabin
         Cabin = replace(Cabin, is.na(Cabin), 0)) %>% 
  mutate(Cabin = as_factor(Cabin))  

# Dropping missing value
titanic_data <- titanic_data[complete.cases(titanic_data), ]

# Descriptive analysis
describe(titanic_data)
summary(titanic_data)
```

### Checking data

#### Exploratory analysis
```{r}
# Survived
Fig_Survived <- titanic_data %>% ggplot(aes(x = Survived)) + geom_bar(fill = "white", colour = "black")

# Survived : Pclass3
Fig_Survived_Pclass3 <- titanic_data %>% ggplot(aes(x = Pclass3, fill = Survived)) +	geom_bar()

# Survived : Sex
Fig_Survived_Sex <- titanic_data %>% 	ggplot(aes(x = Sex, fill = Survived)) +	geom_bar()

# Survived : Age
Fig_Survived_Age <- titanic_data %>% ggplot() + aes(x = Age) + 
  geom_histogram(fill = "white", colour = "black") + facet_grid(Survived ~ .)

# Survived : Cabin
Fig_Survived_Cabin <- titanic_data %>% 	ggplot(aes(x = Cabin, fill = Survived)) + geom_bar()

# Survived : SibSp
Fig_Survived_SibSp <- titanic_data %>% ggplot() + aes(x = SibSp) + 
  geom_histogram(fill = "white", colour = "black") + facet_grid(Survived ~ .)

# Survived : Parch
Fig_Survived_Parch <- titanic_data %>% ggplot() + aes(x = Parch) + 
  geom_histogram(fill = "white", colour = "black") + facet_grid(Survived ~ .)

# Survived : Fare
Fig_Survived_Fare <- titanic_data %>% ggplot() + aes(x = Fare) + 
  geom_histogram(fill = "white", colour = "black") + facet_grid(Survived ~ .)

# Survived : Embarked
Fig_Survived_Embarked <- titanic_data %>% 	ggplot(aes(x = Embarked, fill = Survived)) + geom_bar()

ggarrange(Fig_Survived,Fig_Survived_Age,Fig_Survived_Fare,Fig_Survived_SibSp,Fig_Survived_Parch,Fig_Survived_Embarked,Fig_Survived_Cabin,Fig_Survived_Pclass3,Fig_Survived_Sex,labels = c("Distribution of Survived", "Survived x Age", "Survived x Fare", "Survived x SibSp", "Survived x Parch", "Survived x Embarked", "Survived x Cabin", "Survived x Pclass3", "Survived x Sex"),font.label = list(size = 10, face = "bold"), label.y = 1.05, ncol = 3, nrow = 3)
```


### Regrrssion model

```{r}
mod1 <- glm(Survived ~ Pclass3 + Sex + Age + SibSp + Parch + Cabin, family = binomial(), data = titanic_data)
summary(mod1)
coef(mod1)
exp(coef(mod1))
exp(confint(mod1))

```

### Prediction accuracy

```{r}
titanic_data %>%
  group_by(Survived) %>%
  summarise(count = n()) %>%
  mutate(freq = count / sum(count))

titanic_data <- titanic_data %>% 
  mutate(pred_mod1 = predict(mod1)) %>% 
  mutate(pred_mod1 = case_when(pred_mod1 <= 0 ~ "died",
                               pred_mod1 > 0 ~ "survived")) 

titanic_data = titanic_data %>% 
  mutate(correct_prediction = case_when(pred_mod1 == Survived ~ "correct",
                                        pred_mod1 != Survived ~ "incorrect"))

titanic_data %>% 
  group_by(correct_prediction) %>% 
  summarise(count = n()) %>% 
  mutate(freq =  count / sum(count))   # overall accurcy: 81.2%

titanic_data %>% 
  filter(Survived == "died") %>% 
  group_by(correct_prediction) %>% 
  summarise(count = n()) %>% 
  mutate(freq = count / sum(count)) # accuracy(died): 86.6%

titanic_data %>% 
  filter(Survived == "survived") %>% 
  group_by(correct_prediction) %>% 
  summarise(count = n()) %>% 
  mutate(freq = count / sum(count)) # accuracy(survived): 73.3%
```

### Survival probability for Sue and Kate
```{r}
# Sue and Kate had 3rd class ticket(Pclass3=1), and didn't get the cabins(Cabin=0). Sue was 4 and Kate was 20 at the time.

# Equation: Survived=0.24-1.32*Pclass3 (Pclass3=1)+2.60*Sex (Female)-0.04*Age-0.34*Sibsp-0.06*Parch+1.29*Cabin (Cabin=1)


# Sue's chance of survival with Leonardo
0.24-1.32*1+2.60*1-0.04*4-0.34*0-0.06*2+1.29*0  # log-odds = 1.24
exp(1.24)/(1+exp(1.24)) # p = 0.775564

# Sue's chance of survival without Leonardo
0.24-1.32*1+2.60*1-0.04*4-0.34*0-0.06*1+1.29*0  # log-odds = 1.3
exp(1.3)/(1+exp(1.3)) # p = 0.785835


# Kate's chance of survival with Leonardo
0.24-1.32*1+2.60*1-0.04*20-0.34*1-0.06*1+1.29*0  # log-odds = 0.32
exp(0.32)/(1+exp(0.32)) # p = 0.5793243

# Kate's chance of survival without Leonardo
0.24-1.32*1+2.60*1-0.04*20-0.34*0-0.06*1+1.29*0  # log-odds = 0.66
exp(0.66)/(1+exp(0.66)) # p = 0.6592604
```

### Model performance

```{r}
# Model performance
pR2(mod1)  # McFadden R^2: 0.3376216
pR2(mod1)["llh"] * -2  # -2ll: 636.4819

# Null model
mod_null = glm(Survived ~ 1, family = binomial(), data = titanic_data)
summary(mod_null)

# Likelihood ratio test
lrtest(mod_null, mod1)

# AIC
AIC(mod_null, mod1)
```

### Relative contribution of predictors to the model

```{r}
dominance_mod1 = dominanceAnalysis(mod1)
contributionByLevel(dominance_mod1, fit.functions="r2.m")
averageContribution(dominance_mod1,fit.functions = "r2.m")
plot(dominance_mod1, which.graph ="general",fit.function = "r2.m") + coord_flip()
```